name: flutter_flat_app
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  barcode_scan: 0.0.8
  qr_flutter: 1.1.6
  path_provider:  0.5.0+1
  camera: 0.4.0+1
  web3dart: ^0.4.5
  intl: 0.15.7
  google_maps_flutter: 0.2.0
  location: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.0
  shared_preferences: ^0.4.3
  google_maps_flutter: 0.2.0

      # image_picker: 0.1.1                                             # new
#  google_sign_in: 0.3.1                                           # new
#  firebase_analytics: 1.0.4                                       # new
                                               # new
#   firebase_database: 0.0.12                                       # new
#  firebase_storage: 0.0.5                                         # new

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/QrCode.ttf
    - assets/login-background.jpg
    - assets/abi/GemERC721.json
    - assets/abi/contracts_Test_sol_Test.abi
    - assets/abi/contracts_CapsuleEscrow_sol_CapsuleEscrow.abi
    - assets/login-image.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `packages/PACKAGE_NAME/`. The `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: QrCode
      fonts:
        - asset: assets/QrCode.ttf
